In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast

In [21]:
df = pd.read_csv('../paralela.csv', index_col=0)

residual = 11.1111
df['Média'] = df['Média'] - residual
display(df)

df.to_csv("ativo-Rmax-paralelo.csv")

,Stress-ng,Média,Variância,método,método2,par,cpu,tempo,data
0,stress-ng---cpu-3---cpu-method-ackermann--t-30...,13.079833,0.010985,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
2,stress-ng---cpu-3---cpu-method-ackermann--t-30...,13.071685,0.030873,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
4,stress-ng---cpu-3---cpu-method-ackermann--t-30...,13.062382,0.023777,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
6,stress-ng---cpu-3---cpu-method-ackermann--t-30...,13.098945,0.009455,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
8,stress-ng---cpu-3---cpu-method-ackermann--t-30...,13.100447,0.009224,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
...,...,...,...,...,...,...,...,...,...
540,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,8.918261,0.016672,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
542,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,8.746661,0.014760,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
544,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,8.864936,0.015714,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
546,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,8.787830,0.018781,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
548,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,8.940898,0.013574,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress

In [24]:

df = pd.read_csv('../paralela.csv', index_col=0)

residual = 9.5762
df['Média'] = df['Média'] - residual
display(df)

df.to_csv("ativo-Rmin-paralelo.csv")

,Stress-ng,Média,Variância,método,método2,par,cpu,tempo,data
0,stress-ng---cpu-3---cpu-method-ackermann--t-30...,14.614733,0.010985,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
2,stress-ng---cpu-3---cpu-method-ackermann--t-30...,14.606585,0.030873,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
4,stress-ng---cpu-3---cpu-method-ackermann--t-30...,14.597282,0.023777,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
6,stress-ng---cpu-3---cpu-method-ackermann--t-30...,14.633845,0.009455,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
8,stress-ng---cpu-3---cpu-method-ackermann--t-30...,14.635347,0.009224,ackermann,queens,"('ackermann', 'queens')",-cpu-3,30,stress
...,...,...,...,...,...,...,...,...,...
540,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,10.453161,0.016672,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
542,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,10.281561,0.014760,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
544,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,10.399836,0.015714,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
546,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,10.322730,0.018781,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress
548,stress-ng---cpu-3---cpu-method-rand--t-30-stre...,10.475798,0.013574,rand,jmp,"('jmp', 'rand')",-cpu-3,30,stress

In [ ]:
# o código abaixo agrega o consumo ativo sequencial e calcula a média por método

df_max = pd.read_csv("ativo-Rmax-sequencial.csv")
df_min = pd.read_csv("ativo-Rmin-sequencial.csv")

df_media_sequencial_max = df_max.groupby('método')['Média'].mean()
display(df_media_sequencial_max)
df_media_sequencial_max.to_csv("media_sequencial_max.csv")

df_media_sequencial_min = df_min.groupby('método')['Média'].mean()
display(df_media_sequencial_min)
df_media_sequencial_min.to_csv("media_sequencial_min.csv")

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  55 non-null     int64
 1   Stress-ng   55 non-null     str
 2   Média       55 non-null     float64
 3   Variância   55 non-null     float64
 4   método      55 non-null     str
 5   cpu         55 non-null     str
 6   tempo       55 non-null     int64
 7   data        55 non-null     str
dtypes: float64(2), int64(2), str(4)
memory usage: 3.6 KB

método
ackermann      12.742917
double         13.518503
fibonacci       7.912658
float          11.140528
int64           9.016734
int64double    12.764880
int64float     14.174607
jmp            10.564154
prod           15.921071
queens         13.461133
rand            6.991774
Name: Média, dtype: float64

método
ackermann      14.277817
double         15.053403
fibonacci       9.447558
float          12.675428
int64          10.551634
int64double    14.299780
int64float     15.709507
jmp            12.099054
prod           17.455971
queens         14.996033
rand            8.526674
Name: Média, dtype: float64

In [32]:
# o código abaixo agrega o consumo ativo paralelo e calcula a média por método

df_max = pd.read_csv("ativo-Rmax-paralelo.csv")
df_min = pd.read_csv("ativo-Rmin-paralelo.csv")

df_media_paralelo_max = df_max.groupby('par')['Média'].mean()
df_media_paralelo_max['par'] = df_media_paralelo_max['par'].apply(ast.literal_eval)
display(df_media_paralelo_max)
df_media_paralelo_max.to_csv("media_paralelo_max.csv")

df_media_paralelo_min = df_min.groupby('par')['Média'].mean()
df_media_paralelo_min['par'] = df_media_paralelo_min['par'].apply(ast.literal_eval)
display(df_media_paralelo_min)
df_media_paralelo_min.to_csv("media_paralelo_min.csv")

KeyError: 'par'